const SITE_MAP = {
  douyin: {
    domain: '.douyin.com',
    url: 'https://www.douyin.com/',
  },
  xiaohongshu: {
    domain: '.xiaohongshu.com',
    url: 'https://www.xiaohongshu.com/',
  },
};

function status(message, type = 'info') {
  const el = document.getElementById('status');
  el.textContent = message;
  el.className = 'status ' + type;
}

function cookieToNetscapeLine(cookie, fallbackDomain) {
  const domain = cookie.domain || fallbackDomain;
  const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
  const path = cookie.path || '/';
  const secure = cookie.secure ? 'TRUE' : 'FALSE';
  const expiration = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 1893456000;
  return [domain, includeSubdomains, path, secure, expiration, cookie.name, cookie.value].join('\t');
}

async function exportCookies() {
  const site = SITE_MAP[document.getElementById('site').value];
  const cookies = await chrome.cookies.getAll({ domain: site.domain.replace(/^\./, '') });
  if (!cookies.length) {
    status('没有读到 Cookies。请先打开并登录对应网站，再重试。', 'err');
    return '';
  }
  const output = [
    '# Netscape HTTP Cookie File',
    '# Generated by BiliStudy Cookie Helper',
    ...cookies.map((cookie) => cookieToNetscapeLine(cookie, site.domain)),
  ].join('\n');
  document.getElementById('output').value = output;
  status(`已读取 ${cookies.length} 条 Cookies`, 'ok');
  return output;
}

async function copyCookies() {
  const text = document.getElementById('output').value || await exportCookies();
  if (!text) return;
  await navigator.clipboard.writeText(text);
  status('已复制 cookies.txt 内容', 'ok');
}

async function saveToBiliStudy() {
  const cookiesText = document.getElementById('output').value || await exportCookies();
  if (!cookiesText) return;
  const baseUrl = document.getElementById('baseUrl').value.replace(/\/+$/, '');
  try {
    const resp = await fetch(baseUrl + '/api/config', {
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ yt_dlp_cookies: cookiesText }),
    });
    const data = await resp.json().catch(() => ({}));
    if (!resp.ok || data.success === false) {
      throw new Error(data.error || resp.statusText || '保存失败');
    }
    status('已保存到 BiliStudy 设置', 'ok');
  } catch (err) {
    status('保存失败：请确认已登录 BiliStudy。' + (err.message ? ' ' + err.message : ''), 'err');
  }
}

document.getElementById('exportBtn').addEventListener('click', exportCookies);
document.getElementById('copyBtn').addEventListener('click', copyCookies);
document.getElementById('saveBtn').addEventListener('click', saveToBiliStudy);

chrome.storage.local.get(['baseUrl', 'site'], (data) => {
  if (data.baseUrl) document.getElementById('baseUrl').value = data.baseUrl;
  if (data.site) document.getElementById('site').value = data.site;
});

document.getElementById('baseUrl').addEventListener('change', (e) => chrome.storage.local.set({ baseUrl: e.target.value }));
document.getElementById('site').addEventListener('change', (e) => chrome.storage.local.set({ site: e.target.value }));
